sudo:
  true

language:
  generic

# We need Docker here
services:
  - Docker

# Prepare package manager apt
before_install:
  # - sudo apt-get install apt-file
  # - sudo apt-get -yq update
  - sudo chmod ugo+x scripts/latex_compiler.sh

# Get the latest version of Docker to run on Travis virtual core
install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

# Build the latex embedded Docker image
before_script:
  - docker build -t latex_compiler .

# Run the Docker image in a container
jobs:
  include:
    script: scripts/./latex_compiler.sh

# If latex document successfully build, tag this commit
after_success:
  - export TRAVIS_TAG="Resume_Anmol_Gupta-$(date +'%Y-%m-%d-%H-%M-%S')"
  - git tag $TRAVIS_TAG

# Setup the git configuration details
before_deploy:
  - git config user.name anmolgupta1005
  - git config user.email anmol.gupta1005@gmail.com

# Deploy the resume as a tag in the repo directly from Travis
deploy:
  provider: releases
  api_key: ZawuPKWbS/R9LKg4/uLFfR7bjuNoL2HTFWSYIPUrkb4+7csZ8TeXPnb/6DYASigUBHNTysxzN4XYcKuBdwsW9JcOHlROc7qNaa97cBd4hBK2Ik8n2oIWIWHyFwOQ8mZKHdmiJte9iEsq7eYHbxzLEbR92VD4Rc2yl3TV5aRfZXz7SWUXUzdhHwU/kPZOgQKqNkqCrif6rde44EOafRMG8iQ40Ngps2ePazOWiMp88dyn7SrARMiwPi77av6GPQfzBjaO3B1lcyU7U07JVlNLWKMhsIhN0tHlYRP8kRp5v12Lkj69jkOoTvTacKDXJCyhd5zKP6BAHgTbC5ZDPp1xy2GnPuXFWhs/Fl551rGQYl4b8Jz/1pQkBtYo1GcXgN3UrAhE7q87l4YgCWGS62wUzOYMJ92k6Ts0oOFAKMu8t7flmrcwY2oRbzOey6gfVXHUKlYM9Mv/UZq7kNySFCws9oNg0ajHuVlhzId9Jk/cHAyNrHaqKCXqfOVCm24JRXoZb2Or/Lv6MtmNnoOvSW+0sqczduALCBmZr5J6i6sa6npd/t7/1PeOCOZ8LiylvTTYSVJ2+PYAwk7QdtzCFGJuTbeZIKZIvCn5bqFL8ARlys8YJ4Lw7h+/q49hh4WLZTeZnJ3g9L3RJmfzxX9yYw0x5pi0yTZHqntIpTans9nMqoI=
  file: Resume_Anmol_Gupta.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: anmolgupta1005/Resume-II
    branches:
      only: master

