sudo:
  true

language:
  generic

# We need Docker here
services:
  - Docker

# Prepare package manager apt
before_install:
#  - sudo apt-get install apt-file
#  - sudo apt-get -yq update
  - sudo chmod ugo+x scripts/latex_compiler.sh

# Get the latest version of Docker to run on Travis virtual core
install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

# Build the latex embedded Docker image
before_script:
  - docker build -t latex_compiler .

# Run the Docker image in a container
jobs:
  include:
    script: scripts/./latex_compiler.sh

# If latex document successfully build, tag this commit
after_success:
  - export TRAVIS_TAG="Resume_Anmol_Gupta:$(date +'%Y/%m/%d-%H:%M:%S')"
  - git tag $TRAVIS_TAG

# Setup the git configuration details
before_deploy:
  - git config user.name anmolgupta1005
  - git config user.email anmol.gupta1005@gmail.com

# Deploy the resume as a tag in the repo directly from Travis
deploy:
  provider: releases
  api_key:
    secure: Dyg6O2nufzuIfYkjmTV5gR2bfnGK4A5nXbBPZXWj4yekRHiBxp+xLtWANfsFpG2zwtbj/a6cCFbSAcINaa8c3CokzSAkN6yfIC8H73/7TBU7m3F7C50DSGsuSVygZxnZnYFaOa5GD6kR/Uc59jAVj274HbZ7Gdux8YPAq+Y7AeXfz2N7TmTa3iJZ6/Vx/ZRxNQY4/qoHmSvyHjHJrhvX2Sh+Dmdyu2n/1amtvhxMg62p5bjM4CtAITTSmmhAX0zU03cRjhLi9tcdiwrvs82PkvXY/CSOHhjKBMwGRMhbjuL50yZ3RJ6bbiW2UzzLFMFOEPLuVK26Pv4eYzTlEIg1eAobfwDK3eK6idZ/0RcKXoYB1ZjbBjtNoV/UUo/v82IeepRf7LsD5DWv/xN1oHOMHVfEJtOT8qGrGgPVzJh14v2SzVa3E33Vg8SXIpGRzAc2LtNCGFPQONjXWj6UhkZn8yqS1Y+OVTnuOM72qbP2UtNnt3WW0QhvP9psCO04B5vJeaK+YYFPqhflDOYe/RwuAL3K+zUFR6INU4C0l8DlzNvsfjO+BiSjma4N5dmW2YOFQMAPMCtF8ZU2XHMwwI4pbqDYbWhvIlGW1GXUh+z9WbYV1ER+E41W+nCKPHa+FWCUqTHuyvqmR8hA8u3ToUBJCVGC39L50sEjdPR6+9qhTsM=
  file: Resume_Anmol_Gupta.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: anmolgupta1005/Resume-II
    branches:
      only: master

